#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sun Oct 05 01:00:52 PKT 2025
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 08b596c6f8f443ee920a06426cfe4dcf --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot comparator_8_biit_tb_behav xil_defaultlib.comparator_8_biit_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto 08b596c6f8f443ee920a06426cfe4dcf --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot comparator_8_biit_tb_behav xil_defaultlib.comparator_8_biit_tb xil_defaultlib.glbl -log elaborate.log

